server:
  port: 9999
#  servlet:
#    context-path: /thinking

#jasypt:
#  encryptor:
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator

logging:
  config: classpath:log/logback.xml

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

spring:
  datasource:
    name: auth
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/NUMS?useUnicode=true&characterEncoding=utf-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  application:
    name: Main-Process
  cloud:
    config:
      fail-fast=true
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: swsk33
    password: 12345


springdoc:
  show-actuator: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      where-strategy: NOT_NULL

thinking:
  auth:
    white-list:
      - /login
      - /test
      # start 接口文档相关
      - /doc.html
      - /favicon.ico
      - /webjars/**
      - /v3/api-docs/*
      - /v3/api-docs
      - /eureka/
      # end
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true